#!/usr/bin/env python3
"""
build_contests.py — generate public_html/tr4w_contests.html

Single source of truth: the TR4W program's ContestsArray in the TR4W source
(tr4w/src/VC.pas). Each record carries the contest Name, its WA7BNM ref id, and a
FriendlyName. We parse that array and render a themed, filterable HTML table.

Per contest:
  - column 1 (TR4W Name) = the program's Name field (with the {comment} braces
    stripped).
  - column 2 (Contest)   = FriendlyName, or the Name when FriendlyName is empty;
                           rendered as a link to contestdetails.php?ref=<WA7BNM>
                           when WA7BNM > 0, otherwise plain text.

The 'DUMMY CONTEST' placeholder record is skipped. There is no separate friendly
table or overrides file any more — edit the contest data in the program.

Usage:
  python3 tools/contests/build_contests.py
  python3 tools/contests/build_contests.py --vc /path/to/tr4w/src/VC.pas
"""
import argparse
import html
import re
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parents[1]
DETAIL = "https://www.contestcalendar.com/contestdetails.php?ref="
DEFAULT_VC = Path.home() / "projects" / "TR4W" / "tr4w" / "src" / "VC.pas"


_NAME = re.compile(r"[({]\s*Name:\s*'([^']*)'")     # Name preceded by ( or { (not FriendlyName)
_WA7BNM = re.compile(r"WA7BNM:\s*(\d+)")
_FRIENDLY = re.compile(r"FriendlyName:\s*'([^']*)'")


def parse_vc(path):
    """Parse the ContestsArray records from the TR4W source (VC.pas).

    Returns [(name, wa7bnm_id, friendly), ...] in array order, skipping the
    DUMMY CONTEST placeholder. A record line is one carrying both a WA7BNM field
    and a FriendlyName field.
    """
    contests = []
    for line in path.read_text(encoding="latin-1").splitlines():
        if "WA7BNM:" not in line or "FriendlyName:" not in line:
            continue
        nm = _NAME.search(line)
        wa = _WA7BNM.search(line)
        fn = _FRIENDLY.search(line)
        name = nm.group(1).strip() if nm else ""
        wid = int(wa.group(1)) if wa else 0
        friendly = fn.group(1).strip() if fn else ""
        if name == "DUMMY CONTEST":
            continue
        contests.append((name, wid, friendly))
    return contests


def render(contests):
    out_rows = []
    linked = 0
    for name, wid, friendly in contests:
        display = friendly or name          # fall back to Name when no FriendlyName
        search = html.escape((name + " " + display).lower(), quote=True)
        if wid > 0:
            linked += 1
            cell = ('<a href="%s%d" target="_blank" rel="noopener">%s</a>'
                    % (DETAIL, wid, html.escape(display)))
        else:
            cell = html.escape(display)
        out_rows.append(
            '      <tr data-search="%s"><td class="name">%s</td>'
            '<td class="friendly">%s</td></tr>'
            % (search, html.escape(name), cell)
        )
    page = (TEMPLATE
            .replace("__ROWS__", "\n".join(out_rows))
            .replace("__TOTAL__", str(len(contests)))
            .replace("__RESOLVED__", str(linked)))
    return page, linked


def main():
    ap = argparse.ArgumentParser(description="Build tr4w_contests.html from the TR4W ContestsArray")
    ap.add_argument("--vc", type=Path, default=DEFAULT_VC,
                    help="path to the TR4W source file VC.pas")
    ap.add_argument("--out", type=Path, default=REPO_ROOT / "public_html" / "tr4w_contests.html")
    args = ap.parse_args()

    if not args.vc.exists():
        sys.exit("ERROR: TR4W source not found: %s\n"
                 "       Pass --vc <path to tr4w/src/VC.pas>." % args.vc)

    contests = parse_vc(args.vc)
    page, linked = render(contests)
    args.out.write_text(page)
    print("wrote %s  (%d contests, %d linked, %d name-only)"
          % (args.out, len(contests), linked, len(contests) - linked))


TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<!-- ============================================================
     AUTO-GENERATED — DO NOT EDIT THIS FILE BY HAND.
     Built by tools/contests/build_contests.py from the TR4W program's
     ContestsArray (tr4w/src/VC.pas): Name, WA7BNM id, FriendlyName.
     Edit contest data in the program, not here. Hand edits to THIS
     file are overwritten on the next regeneration.
     ============================================================ -->
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>TR4W — Supported Contests</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Share+Tech+Mono&family=Barlow:wght@300;400;600;700&family=Barlow+Condensed:wght@700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="site.css?v=1">
<style>
  main { max-width: 940px; margin: 0 auto; padding: 4rem 1.5rem 5rem; }
  .page-label { font-family: var(--mono); font-size: 0.8rem; color: var(--green-dim);
    letter-spacing: 0.15em; text-transform: uppercase; margin-bottom: 0.75rem; }
  h1 { font-family: var(--display); font-weight: 800; font-size: clamp(2.2rem, 6vw, 3.4rem);
    line-height: 1; text-transform: uppercase; color: var(--text); margin-bottom: 1rem; }
  h1 .blink { color: var(--green); }
  .lead { color: var(--muted); max-width: 60ch; margin-bottom: 2rem; }
  .lead strong { color: var(--text); }

  .toolbar { display: flex; align-items: center; gap: 1rem; flex-wrap: wrap;
    margin-bottom: 1rem; }
  #filter { flex: 1 1 260px; background: var(--surface); color: var(--text);
    border: 1px solid var(--border); border-radius: 4px; padding: 0.65rem 0.9rem;
    font-family: var(--mono); font-size: 0.95rem; }
  #filter:focus { outline: none; border-color: var(--border-bright); }
  #filter::placeholder { color: var(--muted); }
  .count { font-family: var(--mono); font-size: 0.85rem; color: var(--muted);
    white-space: nowrap; }

  table { width: 100%; border-collapse: collapse; }
  thead th { position: sticky; top: 56px; background: var(--bg);
    text-align: left; font-family: var(--mono); font-size: 0.75rem;
    text-transform: uppercase; letter-spacing: 0.1em; color: var(--green-dim);
    padding: 0.6rem 0.8rem; border-bottom: 1px solid var(--border-bright); }
  tbody td { padding: 0.55rem 0.8rem; border-bottom: 1px solid rgba(57,255,106,0.07);
    vertical-align: top; }
  tbody tr:hover { background: var(--surface2); }
  td.name { font-family: var(--mono); font-size: 0.9rem; color: var(--text);
    white-space: nowrap; }
  td.friendly a { color: var(--green); text-decoration: none; }
  td.friendly a:hover { text-decoration: underline; }
  td.friendly:empty::after { content: '—'; color: var(--muted); opacity: 0.45; }
  #noresults { display: none; color: var(--muted); font-family: var(--mono);
    padding: 1.5rem 0.8rem; }
  .note { margin-top: 1.75rem; font-size: 0.85rem; color: var(--muted); }
  .note a { color: var(--green); }

  @media (max-width: 560px) { td.name { white-space: normal; } nav ul { gap: 1.1rem; } }
</style>
</head>
<body>

<nav>
  <a class="nav-logo" href="index.html">TR4W<span>_</span></a>
  <ul>
    <li><a href="index.html">Home</a></li>
    <li><a href="whytr4w.html">Why TR4W</a></li>
    <li><a href="tr4w_contests.html">Contests</a></li>
    <li><a href="index.html#download">Download</a></li>
    <li><a href="https://github.com/TR4W/TR4W" target="_blank">GitHub &#8599;</a></li>
  </ul>
</nav>

<main>
  <div class="page-label">// reference</div>
  <h1>Supported Contests<span class="blink">_</span></h1>
  <p class="lead">TR4W has built-in support for these <strong>__TOTAL__</strong> contests.
     Use the <em>TR4W name</em> when selecting a contest in the logger; resolved names link to
     the full schedule and rules at WA7BNM's Contest Calendar. A blank in the Contest column just
     means it isn't matched to the calendar yet.</p>

  <div class="toolbar">
    <input id="filter" type="search" placeholder="Filter contests&hellip;" autocomplete="off" spellcheck="false">
    <span class="count" id="count"></span>
  </div>

  <table>
    <thead><tr><th>TR4W Name</th><th>Contest</th></tr></thead>
    <tbody id="rows">
__ROWS__
    </tbody>
  </table>
  <div id="noresults">No contests match that filter.</div>

  <p class="note">Friendly names and schedule links courtesy of the
    <a href="https://www.contestcalendar.com/" target="_blank" rel="noopener">WA7BNM Contest Calendar</a>
    (<span id="resolved">__RESOLVED__</span> of __TOTAL__ matched).</p>
</main>

<footer>
  <p class="f-logo">TR4W_</p>
  <p>&copy; TR4W Project &middot; Free &amp; Open Source</p>
</footer>

<script>
  var inp = document.getElementById('filter');
  var rows = Array.prototype.slice.call(document.querySelectorAll('#rows tr'));
  var countEl = document.getElementById('count');
  var noRes = document.getElementById('noresults');
  function update() {
    var q = inp.value.trim().toLowerCase();
    var visible = 0;
    for (var i = 0; i < rows.length; i++) {
      var show = !q || rows[i].getAttribute('data-search').indexOf(q) !== -1;
      rows[i].style.display = show ? '' : 'none';
      if (show) visible++;
    }
    countEl.textContent = visible + ' / ' + rows.length + ' shown';
    noRes.style.display = visible ? 'none' : 'block';
  }
  inp.addEventListener('input', update);
  update();
</script>
</body>
</html>
"""


if __name__ == "__main__":
    main()
